spring:
  application:
    name: mywuwu-ribbon
server:
  port: 8072
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
    healthcheck:
      #开启健康检查（需要spring-boot-starter-actuator依赖）
       enabled: true
    registry-fetch-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

service-B:
  ribbon:
    NFLoadBalancerRuleClassName: com.netflix.loadbalancer.RoundRobinRule
#zuul:
#  host:
#    socket-timeout-millis: 600000
#    connect-timeout-millis: 600000
#
#hystrix:
#  command:
#    default:
#      execution:
#        isolation:
#          thread:
#            timeoutInMilliseconds: 600000
#ribbon:
#  ReadTimeout: 600000
#  ConnectTimeout: 600000

#ribbon.eureka.enabled=false
