spring:
  application:
    name: muwuwu_service_a
  zipkin:
    base-url: http://localhost:8088
server:
  port: 8076

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/