spring:
  application:
    name: mywuwu-zuul
server:
  port: 8073
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8071/eureka/
    healthcheck:
        #开启健康检查（需要spring-boot-starter-actuator依赖）
      enabled: true
    registry-fetch-interval-seconds: 2
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2

# routes to serviceId
zuul:
#  ignored-services: '*'
  routes:
    mywuwu_service:
       path: /mywuwu_service/**
       serviceId: mywuwu-service
    mywuwu_ribbon:
      path: /mywuwu_ribbon/**
      serviceId: mywuwu-ribbon
    muwuwu_service_a:
      path: /muwuwu_service_a/**
      serviceId: muwuwu-service-a

  host:
    socket-timeout-millis: 30000
    connect-timeout-millis: 30000

hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 600000
ribbon:
  ReadTimeout: 30000
  ConnectTimeout: 30000
  #对当前服务的重试次数
  MaxAutoRetries: 2
#切换相同Server的次数
  MaxAutoRetriesNextServer: 0
